require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class Scraper 
	attr_reader :rows, :ids, :noko
	def initialize
		@rows = []
	end

	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line|
			line =~ /state:wa/
		end.reject do |line|
			line =~ /place:/
		end.map do |line|
		  line.gsub(/,.+/, '').gsub(/\n/, '')
		end 
	end 

	def fetch_map
		page = RestClient.get("http://www.sos.wa.gov/elections/auditors.aspx")
		@noko = Nokogiri::HTML(page) 
	end

	def iterate_through_map
		i = 0
		while i < 39 do #from Adams (at index 0) to Yakima County (at 38), there are 39
			county_name = noko.css('.modal-title')[i].text
			office = county_name + " Elections"
			phone = noko.css('.modal-body')[i].css('li')[0].text.gsub('Phone: ', '')
			website = noko.css('.modal-body')[i].css('li')[3].text.gsub('Website: ', '') || ""
			id = @ids.find do |i| 
				name = county_name.rstrip.gsub(" County", "").gsub(" ", "_")
				i =~ /county:#{name}/i
			end || ""
			i += 1
			@rows << [county_name, "Washington", office, phone, website, id]	
		end


	end			

	def write_into_CSV_file
		CSV.open("spreadsheet.csv", "wb") do |csv|
			@rows.map do |line|
				csv << line
			end
		end
	end

end

a = Scraper.new
a.get_ocd_ids
a.fetch_map
a.iterate_through_map
a.write_into_CSV_file
